apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-podx-config
data:
  telegraf.conf: |+
    [global_tags]
    [agent]
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "20s"
      flush_jitter = "0s"
      precision = ""
      hostname = "k8s-telegraf-podx"
      omit_hostname = false

    [[inputs.ping]]   
      interval = "20s"
      urls = ["google.com"]
      count = 200
      ping_interval = 0.1
      timeout = 1.0
      deadline = 25

    [[inputs.http_response]]
      interval = "10s"
      urls = ["http://google.com"]

    [[inputs.exec]]   
      interval = "60s"
      commands=["mtr -C -n google.com"]
      timeout = "40s"
      data_format = "csv"
      csv_skip_rows = 1
      csv_column_names=["", "", "status", "dest", "hop", "ip", "loss", "snt", "", "", "avg", "best", "worst", "stdev"]
      name_override = "mtr"
      csv_tag_columns = ["dest", "hop", "ip"]

    [[outputs.prometheus_client]]
      listen = ":9126"
      metric_version = 2
      path = "/podx-metrics"

    [[aggregators.histogram]]
      period = "20s"
      drop_original = false
      reset = false
      
    [[aggregators.histogram.config]]
      buckets = [0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.3,2.5,2.7,3.0,5.0,10.0,20.0,30.0,50.0,70.0,100.0]
      measurement_name = "ping"
